# Generated by Django 3.2.6 on 2021-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='educational_background',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='objective',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(),
        ),
    ]
